Repository slipstream/SlipStreamWebUI, pull requests merged in 2018-04, with the labels that each got.

#128 avoid issues related to long usernames
  src/cljs/sixsq/slipstream/webui/authn/views.cljs
  src/cljs/sixsq/slipstream/webui/main/views.cljs
  src/cljs/sixsq/slipstream/webui/profile/views.cljs
  src/cljs/sixsq/slipstream/webui/utils/general.cljs
Labels: P45 MF2C, S40 Ready to validate, T5 Bug

#129 remove xml utils; refactor others
  src/cljs/sixsq/slipstream/webui/editor/editor.cljs
  src/cljs/sixsq/slipstream/webui/plot/plot.cljs
  src/cljs/sixsq/slipstream/webui/utils/general.cljs
Labels: P45 MF2C, S40 Ready to validate, T2 Task

#130 separate dropdown and login button
  src/cljs/sixsq/slipstream/webui/authn/views.cljs
Labels: P45 MF2C, S40 Ready to validate, T5 Bug

#131 format aggregations
  src/cljs/sixsq/slipstream/webui/cimi/views.cljs
Labels: P45 MF2C, S40 Ready to validate, T2 Task

#132 initial prototype of electron application
  .gitignore
  README.md
  project.clj
  resources/public/electron.html
  src/cljs/sixsq/slipstream/webui/electron/main.cljs
  src/cljs/sixsq/slipstream/webui/electron/renderer.cljs
Labels: P45 MF2C, S40 Ready to validate, T2 Task

#134 fix metric plots
  pom.xml
  src/cljs/sixsq/slipstream/webui/metrics/views.cljs
  src/cljs/sixsq/slipstream/webui/utils/general.cljs
  test/cljs/sixsq/slipstream/webui/core_test.cljs
  test/cljs/sixsq/slipstream/webui/runner.cljs
  test/cljs/sixsq/slipstream/webui/utils/general_test.cljs
Labels: P45 MF2C, S40 Ready to validate, T5 Bug

#136 drag/drop and file selector components
  src/cljs/sixsq/slipstream/webui/core.cljs
  src/cljs/sixsq/slipstream/webui/dnd/utils.cljs
  src/cljs/sixsq/slipstream/webui/dnd/views.cljs
  src/cljs/sixsq/slipstream/webui/i18n/dictionary.cljs
Labels: P45 MF2C, S40 Ready to validate, T3 Enhancement

#135 terminate run button is not working
  src/cljs/sixsq/slipstream/webui/history/utils.cljs
  src/cljs/sixsq/slipstream/webui/main/views.cljs
  src/cljs/sixsq/slipstream/webui/routes.cljs
Labels: P45 MF2C, S40 Ready to validate, T5 Bug

#137 Lazy loading reusable template cache and signup modal
  project.clj
  src/cljs/sixsq/slipstream/webui/authn/effects.cljs
  src/cljs/sixsq/slipstream/webui/authn/events.cljs
  src/cljs/sixsq/slipstream/webui/authn/spec.cljs
  src/cljs/sixsq/slipstream/webui/authn/subs.cljs
  src/cljs/sixsq/slipstream/webui/authn/views.cljs
  src/cljs/sixsq/slipstream/webui/cimi/effects.cljs
  src/cljs/sixsq/slipstream/webui/cimi/events.cljs
  src/cljs/sixsq/slipstream/webui/cimi/spec.cljs
  src/cljs/sixsq/slipstream/webui/cimi/subs.cljs
  src/cljs/sixsq/slipstream/webui/cimi/utils.cljs
  src/cljs/sixsq/slipstream/webui/cimi/views.cljs
  src/cljs/sixsq/slipstream/webui/cimi_api/effects.cljs
  src/cljs/sixsq/slipstream/webui/cimi_api/utils.cljs
  src/cljs/sixsq/slipstream/webui/i18n/dictionary.cljs
  src/cljs/sixsq/slipstream/webui/routes.cljs
  src/cljs/sixsq/slipstream/webui/utils/forms.cljs
  src/cljs/sixsq/slipstream/webui/utils/semantic_ui.cljs
Labels: S40 Ready to validate

#141 fix typo
  src/cljs/sixsq/slipstream/webui/dashboard/views_vms.cljs
Labels: P45 MF2C, S40 Ready to validate, T5 Bug

#143 Issue #142 placeholders submit request on enter
  src/cljs/sixsq/slipstream/webui/cimi/views.cljs
  src/cljs/sixsq/slipstream/webui/deployment/views.cljs
Labels: S40 Ready to validate
