Repository slipstream/SlipStreamWebUI, pull requests merged in 2018-09, with the labels that each got.

#238 allow input field to capture focus in search dropdown
  resources/public/css/webui.css
Labels: P80 HNSciCloud-RHEA, S40 Ready to validate

#236 have filter open by default
  src/cljs/sixsq/slipstream/webui/deployment/spec.cljs
  src/cljs/sixsq/slipstream/webui/nuvlabox/spec.cljs
  src/cljs/sixsq/slipstream/webui/usage/spec.cljs
Labels: P80 HNSciCloud-RHEA, S40 Ready to validate

#239 autoload data
  src/cljs/sixsq/slipstream/webui/usage/views.cljs
Labels: P80 HNSciCloud-RHEA, S40 Ready to validate

#237 filter always open
  src/cljs/sixsq/slipstream/webui/cimi/events.cljs
  src/cljs/sixsq/slipstream/webui/cimi/spec.cljs
  src/cljs/sixsq/slipstream/webui/cimi/subs.cljs
  src/cljs/sixsq/slipstream/webui/cimi/views.cljs
  src/cljs/sixsq/slipstream/webui/deployment/events.cljs
  src/cljs/sixsq/slipstream/webui/deployment/spec.cljs
  src/cljs/sixsq/slipstream/webui/deployment/subs.cljs
  src/cljs/sixsq/slipstream/webui/deployment/views.cljs
  src/cljs/sixsq/slipstream/webui/nuvlabox/events.cljs
  src/cljs/sixsq/slipstream/webui/nuvlabox/spec.cljs
  src/cljs/sixsq/slipstream/webui/nuvlabox/subs.cljs
  src/cljs/sixsq/slipstream/webui/nuvlabox/views.cljs
  src/cljs/sixsq/slipstream/webui/usage/events.cljs
  src/cljs/sixsq/slipstream/webui/usage/spec.cljs
  src/cljs/sixsq/slipstream/webui/usage/subs.cljs
  src/cljs/sixsq/slipstream/webui/usage/views.cljs
Labels: P80 HNSciCloud-RHEA, S40 Ready to validate

#240 remove totals from usage table
  src/cljs/sixsq/slipstream/webui/usage/effects.cljs
  src/cljs/sixsq/slipstream/webui/usage/events.cljs
  src/cljs/sixsq/slipstream/webui/usage/spec.cljs
  src/cljs/sixsq/slipstream/webui/usage/subs.cljs
  src/cljs/sixsq/slipstream/webui/usage/utils.cljs
  src/cljs/sixsq/slipstream/webui/usage/views.cljs
Labels: P80 HNSciCloud-RHEA, S40 Ready to validate

#242 change sliders to toggles
  src/cljs/sixsq/slipstream/webui/dashboard/views_deployments.cljs
  src/cljs/sixsq/slipstream/webui/deployment/views.cljs
  src/cljs/sixsq/slipstream/webui/usage/views.cljs
Labels: P80 HNSciCloud-RHEA, S40 Ready to validate

#244 do not show empty table
  src/cljs/sixsq/slipstream/webui/i18n/dictionary.cljs
  src/cljs/sixsq/slipstream/webui/usage/views.cljs
Labels: P80 HNSciCloud-RHEA, S40 Ready to validate

#247 do not disable date pickers
  src/cljs/sixsq/slipstream/webui/usage/utils.cljs
  src/cljs/sixsq/slipstream/webui/usage/views.cljs
  src/cljs/sixsq/slipstream/webui/utils/time.cljs
Labels: P80 HNSciCloud-RHEA, S40 Ready to validate

#245 Feature/user view quota
  src/cljs/sixsq/slipstream/webui/cimi_api/effects.cljs
  src/cljs/sixsq/slipstream/webui/dashboard/views_deployments.cljs
  src/cljs/sixsq/slipstream/webui/dashboard/views_vms.cljs
  src/cljs/sixsq/slipstream/webui/db/spec.cljs
  src/cljs/sixsq/slipstream/webui/i18n/dictionary.cljs
  src/cljs/sixsq/slipstream/webui/main/views.cljs
  src/cljs/sixsq/slipstream/webui/main/views_sidebar.cljs
  src/cljs/sixsq/slipstream/webui/quota/events.cljs
  src/cljs/sixsq/slipstream/webui/quota/spec.cljs
  src/cljs/sixsq/slipstream/webui/quota/subs.cljs
  src/cljs/sixsq/slipstream/webui/quota/views.cljs
  src/cljs/sixsq/slipstream/webui/utils/semantic_ui_extensions.cljs
Labels: S40 Ready to validate

#256 Add about page
  resources/public/images/by_sixsq_mark_red_on_transparent_128px.png
  resources/public/images/logo_swiss_made_software.png
  resources/public/images/slipstream_logo_red_on_transparent_512px.png
  src/cljs/sixsq/slipstream/webui/about/views.cljs
  src/cljs/sixsq/slipstream/webui/i18n/dictionary.cljs
  src/cljs/sixsq/slipstream/webui/main/views.cljs
Labels: S40 Ready to validate

#255 Fill welcome page
  src/cljs/sixsq/slipstream/webui/about/views.cljs
  src/cljs/sixsq/slipstream/webui/i18n/dictionary.cljs
  src/cljs/sixsq/slipstream/webui/main/views.cljs
  src/cljs/sixsq/slipstream/webui/main/views_sidebar.cljs
  src/cljs/sixsq/slipstream/webui/welcome/views.cljs
Labels: S40 Ready to validate

#257 Change the billable filter to use the billable attribute
  src/cljs/sixsq/slipstream/webui/usage/utils.cljs
Labels: S40 Ready to validate

#258 switch to using chartjs
  project.clj
  resources/public/electron.html
  resources/public/webui.html
  src/cljs/sixsq/slipstream/webui/application/effects.cljs
  src/cljs/sixsq/slipstream/webui/cimi/effects.cljs
  src/cljs/sixsq/slipstream/webui/cimi/subs.cljs
  src/cljs/sixsq/slipstream/webui/cimi_detail/views.cljs
  src/cljs/sixsq/slipstream/webui/core.cljs
  src/cljs/sixsq/slipstream/webui/dashboard/effects.cljs
  src/cljs/sixsq/slipstream/webui/dashboard/events.cljs
  src/cljs/sixsq/slipstream/webui/dashboard/views.cljs
  src/cljs/sixsq/slipstream/webui/dashboard/views_deployments.cljs
  src/cljs/sixsq/slipstream/webui/dashboard/views_vms.cljs
  src/cljs/sixsq/slipstream/webui/db/spec.cljs
  src/cljs/sixsq/slipstream/webui/deployment/events.cljs
  src/cljs/sixsq/slipstream/webui/deployment/views.cljs
  src/cljs/sixsq/slipstream/webui/deployment_detail/gantt.cljs
  src/cljs/sixsq/slipstream/webui/deployment_detail/views.cljs
  src/cljs/sixsq/slipstream/webui/dnd/views.cljs
  src/cljs/sixsq/slipstream/webui/editor/editor.cljs
  src/cljs/sixsq/slipstream/webui/i18n/views.cljs
  src/cljs/sixsq/slipstream/webui/legacy_application/events.cljs
  src/cljs/sixsq/slipstream/webui/legacy_application/views.cljs
  src/cljs/sixsq/slipstream/webui/metrics/views.cljs
  src/cljs/sixsq/slipstream/webui/nuvlabox/utils.cljs
  src/cljs/sixsq/slipstream/webui/nuvlabox_detail/views.cljs
  src/cljs/sixsq/slipstream/webui/plot/effects.cljs
  src/cljs/sixsq/slipstream/webui/plot/events.cljs
  src/cljs/sixsq/slipstream/webui/plot/plot.cljs
  src/cljs/sixsq/slipstream/webui/profile/views.cljs
  src/cljs/sixsq/slipstream/webui/quota/views.cljs
  src/cljs/sixsq/slipstream/webui/utils/collapsible_card.cljs
  src/cljs/sixsq/slipstream/webui/utils/semantic_ui.cljs
  src/cljs/sixsq/slipstream/webui/utils/semantic_ui_extensions.cljs
  src/cljs/sixsq/slipstream/webui/welcome/views.cljs
Labels: P45 MF2C, S40 Ready to validate, T3 Enhancement

#259 make elements consistent with welcome page
  src/cljs/sixsq/slipstream/webui/i18n/dictionary.cljs
  src/cljs/sixsq/slipstream/webui/i18n/views.cljs
  src/cljs/sixsq/slipstream/webui/legal/views.cljs
  src/cljs/sixsq/slipstream/webui/main/spec.cljs
  src/cljs/sixsq/slipstream/webui/main/views.cljs
  src/cljs/sixsq/slipstream/webui/main/views_sidebar.cljs
  src/cljs/sixsq/slipstream/webui/welcome/views.cljs
Labels: S40 Ready to validate, T5 Bug

#261 nuvlabox auto refresh state and add colors for state
  src/cljs/sixsq/slipstream/webui/nuvlabox/events.cljs
  src/cljs/sixsq/slipstream/webui/nuvlabox/utils.cljs
  src/cljs/sixsq/slipstream/webui/nuvlabox/views.cljs
Labels: S40 Ready to validate

#264 update with animation working
  src/cljs/sixsq/slipstream/webui/metrics/spec.cljs
  src/cljs/sixsq/slipstream/webui/metrics/views.cljs
  src/cljs/sixsq/slipstream/webui/plot/plot.cljs
Labels: S40 Ready to validate

#263 paging added for nuvlaboxes
  src/cljs/sixsq/slipstream/webui/dashboard/events.cljs
  src/cljs/sixsq/slipstream/webui/nuvlabox/effects.cljs
  src/cljs/sixsq/slipstream/webui/nuvlabox/events.cljs
  src/cljs/sixsq/slipstream/webui/nuvlabox/spec.cljs
  src/cljs/sixsq/slipstream/webui/nuvlabox/subs.cljs
  src/cljs/sixsq/slipstream/webui/nuvlabox/utils.cljs
  src/cljs/sixsq/slipstream/webui/nuvlabox/views.cljs
  src/cljs/sixsq/slipstream/webui/quota/views.cljs
  src/cljs/sixsq/slipstream/webui/utils/general.cljs
Labels: S40 Ready to validate
