Repository slipstream/SlipStreamWebUI, pull requests merged in 2018-08, with the labels that each got.

#193 sort on usage; minor usage ui fixes
  src/cljs/sixsq/slipstream/webui/acl/views.cljs
  src/cljs/sixsq/slipstream/webui/authn/events.cljs
  src/cljs/sixsq/slipstream/webui/authn/spec.cljs
  src/cljs/sixsq/slipstream/webui/authn/subs.cljs
  src/cljs/sixsq/slipstream/webui/cimi_api/effects.cljs
  src/cljs/sixsq/slipstream/webui/cimi_api/utils.cljs
  src/cljs/sixsq/slipstream/webui/cimi_detail/events.cljs
  src/cljs/sixsq/slipstream/webui/cimi_detail/views.cljs
  src/cljs/sixsq/slipstream/webui/i18n/dictionary.cljs
  src/cljs/sixsq/slipstream/webui/nuvlabox_detail/views.cljs
  src/cljs/sixsq/slipstream/webui/profile/views.cljs
  src/cljs/sixsq/slipstream/webui/usage/events.cljs
  src/cljs/sixsq/slipstream/webui/usage/spec.cljs
  src/cljs/sixsq/slipstream/webui/usage/subs.cljs
  src/cljs/sixsq/slipstream/webui/usage/views.cljs
  src/cljs/sixsq/slipstream/webui/utils/collapsible_card.cljs
  src/cljs/sixsq/slipstream/webui/utils/resource_details.cljs
  src/cljs/sixsq/slipstream/webui/utils/style.cljs
  src/cljs/sixsq/slipstream/webui/utils/table.cljs
  src/cljs/sixsq/slipstream/webui/utils/time.cljs
  src/cljs/sixsq/slipstream/webui/utils/values.cljs
Labels: P45 MF2C, S40 Ready to validate, T2 Task

#195 automatic logout at session expiry and minors
  src/cljs/sixsq/slipstream/webui/authn/effects.cljs
  src/cljs/sixsq/slipstream/webui/authn/events.cljs
  src/cljs/sixsq/slipstream/webui/cimi/views.cljs
  src/cljs/sixsq/slipstream/webui/deployment_detail/utils.cljs
  src/cljs/sixsq/slipstream/webui/nuvlabox/utils.cljs
  src/cljs/sixsq/slipstream/webui/usage/utils.cljs
  src/cljs/sixsq/slipstream/webui/utils/forms.cljs
  src/cljs/sixsq/slipstream/webui/utils/resource_details.cljs
  src/cljs/sixsq/slipstream/webui/utils/response.cljs
  src/cljs/sixsq/slipstream/webui/utils/time.cljs
Labels: S40 Ready to validate

#196 add on-close handler
  src/cljs/sixsq/slipstream/webui/cimi/views.cljs
Labels: P45 MF2C, S40 Ready to validate, T5 Bug

#197 clean up deployment; remove old panels; allow users to see application
  src/cljs/sixsq/slipstream/webui/deployment_detail/views.cljs
  src/cljs/sixsq/slipstream/webui/main/views.cljs
  src/cljs/sixsq/slipstream/webui/profile/views.cljs
  src/cljs/sixsq/slipstream/webui/utils/collapsible_card.cljs
  src/cljs/sixsq/slipstream/webui/utils/resource_details.cljs
  src/cljs/sixsq/slipstream/webui/utils/style.cljs
Labels: P45 MF2C, S40 Ready to validate, T2 Task

#199 update font assets for latest semantic ui
  resources/public/css/themes/default/assets/fonts/brand-icons.eot
  resources/public/css/themes/default/assets/fonts/brand-icons.svg
  resources/public/css/themes/default/assets/fonts/brand-icons.ttf
  resources/public/css/themes/default/assets/fonts/brand-icons.woff
  resources/public/css/themes/default/assets/fonts/brand-icons.woff2
  resources/public/css/themes/default/assets/fonts/icons.eot
  resources/public/css/themes/default/assets/fonts/icons.svg
  resources/public/css/themes/default/assets/fonts/icons.ttf
  resources/public/css/themes/default/assets/fonts/icons.woff
  resources/public/css/themes/default/assets/fonts/icons.woff2
  resources/public/css/themes/default/assets/fonts/outline-icons.eot
  resources/public/css/themes/default/assets/fonts/outline-icons.svg
  resources/public/css/themes/default/assets/fonts/outline-icons.ttf
  resources/public/css/themes/default/assets/fonts/outline-icons.woff
  resources/public/css/themes/default/assets/fonts/outline-icons.woff2
Labels: P45 MF2C, S40 Ready to validate, T5 Bug

#200 add preliminary billable filter
  src/cljs/sixsq/slipstream/webui/i18n/dictionary.cljs
  src/cljs/sixsq/slipstream/webui/usage/effects.cljs
  src/cljs/sixsq/slipstream/webui/usage/events.cljs
  src/cljs/sixsq/slipstream/webui/usage/spec.cljs
  src/cljs/sixsq/slipstream/webui/usage/subs.cljs
  src/cljs/sixsq/slipstream/webui/usage/utils.cljs
  src/cljs/sixsq/slipstream/webui/usage/views.cljs
Labels: P80 HNSciCloud-RHEA, S40 Ready to validate, T2 Task

#201 fix visibility of reports on old UI
  src/cljs/sixsq/slipstream/webui/core.cljs
  src/cljs/sixsq/slipstream/webui/deployment_detail/views.cljs
Labels: P80 HNSciCloud-RHEA, S40 Ready to validate, T5 Bug

#206 format raw vector values
  src/cljs/sixsq/slipstream/webui/profile/views.cljs
  src/cljs/sixsq/slipstream/webui/utils/resource_details.cljs
  src/cljs/sixsq/slipstream/webui/utils/values.cljs
Labels: P45 MF2C, S40 Ready to validate, T5 Bug

#205 do not send message on uninitialized cep
  src/cljs/sixsq/slipstream/webui/cimi/events.cljs
Labels: P45 MF2C, S40 Ready to validate, T5 Bug

#208 improve best practices with webui
  resources/public/webui.html
  src/cljs/sixsq/slipstream/webui/authn/views.cljs
  src/cljs/sixsq/slipstream/webui/cimi/views.cljs
  src/cljs/sixsq/slipstream/webui/dashboard/views_deployments.cljs
  src/cljs/sixsq/slipstream/webui/deployment/views.cljs
  src/cljs/sixsq/slipstream/webui/main/effects.cljs
Labels: P45 MF2C, S40 Ready to validate, T3 Enhancement

#209 initial prototype for responsive behavior
  src/cljs/sixsq/slipstream/webui/main/events.cljs
  src/cljs/sixsq/slipstream/webui/main/spec.cljs
  src/cljs/sixsq/slipstream/webui/main/subs.cljs
  src/cljs/sixsq/slipstream/webui/main/views.cljs
  src/cljs/sixsq/slipstream/webui/utils/responsive.cljs
  src/cljs/sixsq/slipstream/webui/utils/semantic_ui.cljs
Labels: P45 MF2C, S40 Ready to validate, T3 Enhancement

#211 remove storage metering from queries
  src/cljs/sixsq/slipstream/webui/usage/utils.cljs
Labels: P45 MF2C, S40 Ready to validate, T5 Bug

#212 fix broken trash icon
  src/cljs/sixsq/slipstream/webui/dashboard/views_deployments.cljs
Labels: S40 Ready to validate, T5 Bug

#213 use active tab control
  src/cljs/sixsq/slipstream/webui/dashboard/views.cljs
Labels: S40 Ready to validate, T5 Bug

#214 fix section toggle
  src/cljs/sixsq/slipstream/webui/utils/semantic_ui_extensions.cljs
Labels: P45 MF2C, S40 Ready to validate, T5 Bug

#216 wrap single deployment entry in a vector
  src/cljs/sixsq/slipstream/webui/deployment/views.cljs
Labels: P45 MF2C, S40 Ready to validate, T5 Bug

#217 don't use hourly conversion for the price
  src/cljs/sixsq/slipstream/webui/usage/utils.cljs
Labels: P80 HNSciCloud-RHEA, S40 Ready to validate, T5 Bug

#219 disk size is already in GB
  src/cljs/sixsq/slipstream/webui/usage/utils.cljs
Labels: P80 HNSciCloud-RHEA, S40 Ready to validate, T5 Bug

#220 use credential name in list, if available
  src/cljs/sixsq/slipstream/webui/usage/views.cljs
Labels: P80 HNSciCloud-RHEA, S40 Ready to validate, T3 Enhancement
