Repository slipstream/SlipStreamWebUI, pull requests merged in 2018-11, with the labels that each got.

#279 metadata visualization
  project.clj
  src/cljs/sixsq/slipstream/webui/db/spec.cljs
  src/cljs/sixsq/slipstream/webui/docs/events.cljs
  src/cljs/sixsq/slipstream/webui/docs/spec.cljs
  src/cljs/sixsq/slipstream/webui/docs/subs.cljs
  src/cljs/sixsq/slipstream/webui/docs/views.cljs
  src/cljs/sixsq/slipstream/webui/docs_detail/views.cljs
  src/cljs/sixsq/slipstream/webui/i18n/dictionary.cljs
  src/cljs/sixsq/slipstream/webui/main/views.cljs
  src/cljs/sixsq/slipstream/webui/main/views_sidebar.cljs
  src/cljs/sixsq/slipstream/webui/utils/general.cljs
  src/cljs/sixsq/slipstream/webui/welcome/views.cljs
Labels: P66 EU-SEC, S40 Ready to validate

#281 migrate to shadow cljs
  .gitignore
  pom.xml
  project.clj
  resources/public/css/react-datepicker.min.inc.css
  resources/public/webui.html
  shadow-cljs.edn
  src/cljs/sixsq/slipstream/webui/docs/views.cljs
  src/cljs/sixsq/slipstream/webui/docs_detail/views.cljs
  src/cljs/sixsq/slipstream/webui/editor/editor.cljs
  src/cljs/sixsq/slipstream/webui/i18n/dictionary.cljs
  src/cljs/sixsq/slipstream/webui/main/views.cljs
  src/cljs/sixsq/slipstream/webui/main/views_sidebar.cljs
  src/cljs/sixsq/slipstream/webui/plot/plot.cljs
  src/cljs/sixsq/slipstream/webui/utils/resource_details.cljs
  src/cljs/sixsq/slipstream/webui/utils/semantic_ui.cljs
  src/cljs/sixsq/slipstream/webui/utils/time.cljs
  test/clj/sixsq/slipstream/webui/dev_server.clj
  test/cljs/sixsq/slipstream/webui/runner.cljs
  test/cljs/sixsq/slipstream/webui/utils/general_test.cljs
Labels: P66 EU-SEC, S40 Ready to validate

#283 add markdown
  project.clj
  src/cljs/sixsq/slipstream/webui/docs_detail/views.cljs
  src/cljs/sixsq/slipstream/webui/utils/semantic_ui.cljs
Labels: P66 EU-SEC, S40 Ready to validate

#284 add copy to clipboard
  src/cljs/sixsq/slipstream/webui/utils/semantic_ui.cljs
Labels: P66 EU-SEC

#285 monkey patch process variable
  shadow-cljs.edn
  src/cljs/sixsq/slipstream/webui/core.cljs
Labels: P66 EU-SEC, S40 Ready to validate

#287 Appstore base on deployment template and cimi deployment
  src/cljs/sixsq/slipstream/webui/appstore/events.cljs
  src/cljs/sixsq/slipstream/webui/appstore/spec.cljs
  src/cljs/sixsq/slipstream/webui/appstore/subs.cljs
  src/cljs/sixsq/slipstream/webui/appstore/utils.cljs
  src/cljs/sixsq/slipstream/webui/appstore/views.cljs
  src/cljs/sixsq/slipstream/webui/db/spec.cljs
  src/cljs/sixsq/slipstream/webui/deployment/effects.cljs
  src/cljs/sixsq/slipstream/webui/deployment/events.cljs
  src/cljs/sixsq/slipstream/webui/deployment/spec.cljs
  src/cljs/sixsq/slipstream/webui/deployment/subs.cljs
  src/cljs/sixsq/slipstream/webui/deployment/views.cljs
  src/cljs/sixsq/slipstream/webui/deployment_detail/effects.cljs
  src/cljs/sixsq/slipstream/webui/deployment_detail/events.cljs
  src/cljs/sixsq/slipstream/webui/deployment_detail/spec.cljs
  src/cljs/sixsq/slipstream/webui/deployment_detail/subs.cljs
  src/cljs/sixsq/slipstream/webui/deployment_detail/utils.cljs
  src/cljs/sixsq/slipstream/webui/deployment_detail/views.cljs
  src/cljs/sixsq/slipstream/webui/i18n/dictionary.cljs
  src/cljs/sixsq/slipstream/webui/main/events.cljs
  src/cljs/sixsq/slipstream/webui/main/views.cljs
  src/cljs/sixsq/slipstream/webui/main/views_sidebar.cljs
  src/cljs/sixsq/slipstream/webui/nuvlabox/views.cljs
  src/cljs/sixsq/slipstream/webui/quota/views.cljs
  src/cljs/sixsq/slipstream/webui/utils/semantic_ui.cljs
  src/cljs/sixsq/slipstream/webui/utils/semantic_ui_extensions.cljs
Labels: P22 GNSS, P66 EU-SEC, S40 Ready to validate

#289 codemirror for react
  package.json
  src/cljs/sixsq/slipstream/webui/application/views.cljs
  src/cljs/sixsq/slipstream/webui/cimi/views.cljs
  src/cljs/sixsq/slipstream/webui/editor/editor.cljs
  src/cljs/sixsq/slipstream/webui/utils/resource_details.cljs
  src/cljs/sixsq/slipstream/webui/utils/semantic_ui.cljs
  src/cljs/sixsq/slipstream/webui/utils/semantic_ui_extensions.cljs
Labels: S40 Ready to validate

#293 upgrade shadow-cljs, clojurescript, and secretary
  package.json
  project.clj
Labels: P66 EU-SEC, S40 Ready to validate, T2 Task

#260 module actions
  src/cljs/sixsq/slipstream/webui/application/effects.cljs
  src/cljs/sixsq/slipstream/webui/application/events.cljs
  src/cljs/sixsq/slipstream/webui/application/spec.cljs
  src/cljs/sixsq/slipstream/webui/application/subs.cljs
  src/cljs/sixsq/slipstream/webui/application/utils.cljs
  src/cljs/sixsq/slipstream/webui/application/views.cljs
  src/cljs/sixsq/slipstream/webui/appstore/events.cljs
  src/cljs/sixsq/slipstream/webui/i18n/dictionary.cljs
  src/cljs/sixsq/slipstream/webui/main/views.cljs
  src/cljs/sixsq/slipstream/webui/messages/views.cljs
Labels: P45 MF2C, S40 Ready to validate, T3 Enhancement

#296 Task/data workflow
  .gitignore
  scripts/mount-data.py
  scripts/populate-gnss-sos.py
  src/cljs/sixsq/slipstream/webui/application/effects.cljs
  src/cljs/sixsq/slipstream/webui/application/events.cljs
  src/cljs/sixsq/slipstream/webui/application/utils.cljs
  src/cljs/sixsq/slipstream/webui/application/views.cljs
  src/cljs/sixsq/slipstream/webui/appstore/events.cljs
  src/cljs/sixsq/slipstream/webui/appstore/spec.cljs
  src/cljs/sixsq/slipstream/webui/appstore/subs.cljs
  src/cljs/sixsq/slipstream/webui/appstore/utils.cljs
  src/cljs/sixsq/slipstream/webui/appstore/views.cljs
  src/cljs/sixsq/slipstream/webui/data/effects.cljs
  src/cljs/sixsq/slipstream/webui/data/events.cljs
  src/cljs/sixsq/slipstream/webui/data/spec.cljs
  src/cljs/sixsq/slipstream/webui/data/subs.cljs
  src/cljs/sixsq/slipstream/webui/data/utils.cljs
  src/cljs/sixsq/slipstream/webui/data/views.cljs
  src/cljs/sixsq/slipstream/webui/db/spec.cljs
  src/cljs/sixsq/slipstream/webui/deployment/events.cljs
  src/cljs/sixsq/slipstream/webui/deployment/views.cljs
  src/cljs/sixsq/slipstream/webui/deployment_detail/events.cljs
  src/cljs/sixsq/slipstream/webui/deployment_detail/subs.cljs
  src/cljs/sixsq/slipstream/webui/deployment_detail/views.cljs
  src/cljs/sixsq/slipstream/webui/i18n/dictionary.cljs
  src/cljs/sixsq/slipstream/webui/main/views.cljs
  src/cljs/sixsq/slipstream/webui/main/views_sidebar.cljs
  src/cljs/sixsq/slipstream/webui/utils/response.cljs
  src/cljs/sixsq/slipstream/webui/utils/semantic_ui.cljs
  src/cljs/sixsq/slipstream/webui/utils/time.cljs
Labels: S40 Ready to validate

#301 Task/deployment progress in step
  src/cljs/sixsq/slipstream/webui/deployment_detail/events.cljs
  src/cljs/sixsq/slipstream/webui/deployment_detail/spec.cljs
  src/cljs/sixsq/slipstream/webui/deployment_detail/subs.cljs
  src/cljs/sixsq/slipstream/webui/deployment_detail/views.cljs
  src/cljs/sixsq/slipstream/webui/utils/time.cljs
Labels: P22 GNSS, S40 Ready to validate

#303 add jobs to deployment detail
  src/cljs/sixsq/slipstream/webui/deployment_detail/events.cljs
  src/cljs/sixsq/slipstream/webui/deployment_detail/spec.cljs
  src/cljs/sixsq/slipstream/webui/deployment_detail/subs.cljs
  src/cljs/sixsq/slipstream/webui/deployment_detail/views.cljs
  src/cljs/sixsq/slipstream/webui/i18n/dictionary.cljs
Labels: P22 GNSS, S40 Ready to validate, T2 Task
