Repository slipstream/SlipStreamWebUI, pull requests merged in 2018-07, with the labels that each got.

#163 cimi modules
  src/cljs/sixsq/slipstream/webui/application/effects.cljs
  src/cljs/sixsq/slipstream/webui/application/events.cljs
  src/cljs/sixsq/slipstream/webui/application/spec.cljs
  src/cljs/sixsq/slipstream/webui/application/views.cljs
  src/cljs/sixsq/slipstream/webui/db/spec.cljs
Labels: P45 MF2C, S40 Ready to validate, T2 Task

#161 visualization of nuvlabox state
  src/cljs/sixsq/slipstream/webui/cimi_detail/views.cljs
  src/cljs/sixsq/slipstream/webui/db/spec.cljs
  src/cljs/sixsq/slipstream/webui/i18n/dictionary.cljs
  src/cljs/sixsq/slipstream/webui/main/views.cljs
  src/cljs/sixsq/slipstream/webui/metrics/views.cljs
  src/cljs/sixsq/slipstream/webui/nuvlabox/effects.cljs
  src/cljs/sixsq/slipstream/webui/nuvlabox/events.cljs
  src/cljs/sixsq/slipstream/webui/nuvlabox/spec.cljs
  src/cljs/sixsq/slipstream/webui/nuvlabox/subs.cljs
  src/cljs/sixsq/slipstream/webui/nuvlabox/utils.cljs
  src/cljs/sixsq/slipstream/webui/nuvlabox/views.cljs
  src/cljs/sixsq/slipstream/webui/nuvlabox_detail/effects.cljs
  src/cljs/sixsq/slipstream/webui/nuvlabox_detail/events.cljs
  src/cljs/sixsq/slipstream/webui/nuvlabox_detail/spec.cljs
  src/cljs/sixsq/slipstream/webui/nuvlabox_detail/subs.cljs
  src/cljs/sixsq/slipstream/webui/nuvlabox_detail/views.cljs
  src/cljs/sixsq/slipstream/webui/utils/time.cljs
Labels: P45 MF2C, S40 Ready to validate, T3 Enhancement

#165 make new apps tab available only to administrators
  src/cljs/sixsq/slipstream/webui/main/views.cljs
Labels: P45 MF2C, S40 Ready to validate, T2 Task

#167 change authn panels
  src/cljs/sixsq/slipstream/webui/application/views.cljs
  src/cljs/sixsq/slipstream/webui/authn/events.cljs
  src/cljs/sixsq/slipstream/webui/authn/spec.cljs
  src/cljs/sixsq/slipstream/webui/authn/subs.cljs
  src/cljs/sixsq/slipstream/webui/authn/utils.cljs
  src/cljs/sixsq/slipstream/webui/authn/views.cljs
  src/cljs/sixsq/slipstream/webui/cimi/views.cljs
  src/cljs/sixsq/slipstream/webui/core.cljs
  src/cljs/sixsq/slipstream/webui/deployment/views.cljs
  src/cljs/sixsq/slipstream/webui/i18n/dictionary.cljs
  src/cljs/sixsq/slipstream/webui/legacy_application/views.cljs
  src/cljs/sixsq/slipstream/webui/nuvlabox/views.cljs
  src/cljs/sixsq/slipstream/webui/utils/component.cljs
  src/cljs/sixsq/slipstream/webui/utils/form_fields.cljs
  src/cljs/sixsq/slipstream/webui/utils/forms.cljs
  src/cljs/sixsq/slipstream/webui/utils/resource_details.cljs
  src/cljs/sixsq/slipstream/webui/utils/ui_callback.cljs
Labels: P45 MF2C, S40 Ready to validate, T2 Task

#171 render complex values as strings
  src/cljs/sixsq/slipstream/webui/cimi/views.cljs
  src/cljs/sixsq/slipstream/webui/dashboard/views_deployments.cljs
  src/cljs/sixsq/slipstream/webui/dashboard/views_vms.cljs
  src/cljs/sixsq/slipstream/webui/deployment_detail/views.cljs
  src/cljs/sixsq/slipstream/webui/messages/views.cljs
  src/cljs/sixsq/slipstream/webui/utils/form_fields.cljs
  src/cljs/sixsq/slipstream/webui/utils/forms.cljs
  src/cljs/sixsq/slipstream/webui/utils/resource_details.cljs
Labels: P45 MF2C, S40 Ready to validate, T5 Bug

#178 refactor key press handling
  src/cljs/sixsq/slipstream/webui/cimi/views.cljs
  src/cljs/sixsq/slipstream/webui/deployment/views.cljs
  src/cljs/sixsq/slipstream/webui/nuvlabox/views.cljs
  src/cljs/sixsq/slipstream/webui/utils/forms.cljs
Labels: P45 MF2C, S40 Ready to validate, T2 Task

#181 reports not shown in standard UI
  src/cljs/sixsq/slipstream/webui/deployment_detail/views.cljs
Labels: P45 MF2C, S40 Ready to validate, T5 Bug

#182 replace menu by semanticui sidebar
  resources/public/css/webui.css
  src/cljs/sixsq/slipstream/webui/application/views.cljs
  src/cljs/sixsq/slipstream/webui/i18n/views.cljs
  src/cljs/sixsq/slipstream/webui/legacy_application/views.cljs
  src/cljs/sixsq/slipstream/webui/main/views.cljs
  src/cljs/sixsq/slipstream/webui/utils/semantic_ui.cljs
Labels: S40 Ready to validate

#179 update alerts; use slider; allow more detail with modal
  src/cljs/sixsq/slipstream/webui/cimi/views.cljs
  src/cljs/sixsq/slipstream/webui/i18n/dictionary.cljs
  src/cljs/sixsq/slipstream/webui/main/views.cljs
  src/cljs/sixsq/slipstream/webui/messages/events.cljs
  src/cljs/sixsq/slipstream/webui/messages/spec.cljs
  src/cljs/sixsq/slipstream/webui/messages/subs.cljs
  src/cljs/sixsq/slipstream/webui/messages/views.cljs
  src/cljs/sixsq/slipstream/webui/nuvlabox/views.cljs
  src/cljs/sixsq/slipstream/webui/utils/collapsible_card.cljs
  src/cljs/sixsq/slipstream/webui/utils/resource_details.cljs
  src/cljs/sixsq/slipstream/webui/utils/semantic_ui.cljs
Labels: P45 MF2C, S40 Ready to validate, T2 Task

#186 authn forms cleanup
  resources/public/css/semantic.min.css
  resources/public/webui.html
  src/cljs/sixsq/slipstream/webui/authn/utils.cljs
  src/cljs/sixsq/slipstream/webui/authn/views.cljs
  src/cljs/sixsq/slipstream/webui/cimi_api/utils.cljs
Labels: P45 MF2C, S40 Ready to validate, T2 Task

#187 update controls and styles for consistency
  src/cljs/sixsq/slipstream/webui/acl/views.cljs
  src/cljs/sixsq/slipstream/webui/application/views.cljs
  src/cljs/sixsq/slipstream/webui/authn/views.cljs
  src/cljs/sixsq/slipstream/webui/cimi/views.cljs
  src/cljs/sixsq/slipstream/webui/deployment/views.cljs
  src/cljs/sixsq/slipstream/webui/deployment_detail/views.cljs
  src/cljs/sixsq/slipstream/webui/legacy_application/views.cljs
  src/cljs/sixsq/slipstream/webui/messages/views.cljs
  src/cljs/sixsq/slipstream/webui/metrics/views.cljs
  src/cljs/sixsq/slipstream/webui/nuvlabox/spec.cljs
  src/cljs/sixsq/slipstream/webui/nuvlabox/views.cljs
  src/cljs/sixsq/slipstream/webui/nuvlabox_detail/views.cljs
  src/cljs/sixsq/slipstream/webui/profile/views.cljs
  src/cljs/sixsq/slipstream/webui/usage/views.cljs
  src/cljs/sixsq/slipstream/webui/utils/collapsible_card.cljs
  src/cljs/sixsq/slipstream/webui/utils/resource_details.cljs
  src/cljs/sixsq/slipstream/webui/utils/semantic_ui.cljs
  src/cljs/sixsq/slipstream/webui/utils/style.cljs
Labels: P45 MF2C, S40 Ready to validate, T2 Task

#189 basic acl visualization
  src/cljs/sixsq/slipstream/webui/acl/utils.cljs
  src/cljs/sixsq/slipstream/webui/acl/views.cljs
  src/cljs/sixsq/slipstream/webui/nuvlabox_detail/views.cljs
  src/cljs/sixsq/slipstream/webui/utils/resource_details.cljs
  src/cljs/sixsq/slipstream/webui/utils/style.cljs
Labels: P45 MF2C, S40 Ready to validate, T2 Task

#190 provide message for an unknown resource
  src/cljs/sixsq/slipstream/webui/cimi/events.cljs
  src/cljs/sixsq/slipstream/webui/cimi/views.cljs
Labels: P66 EU-SEC, S40 Ready to validate, T5 Bug

#191 Enhance/usage
  src/cljs/sixsq/slipstream/webui/dashboard/views_deployments.cljs
  src/cljs/sixsq/slipstream/webui/i18n/dictionary.cljs
  src/cljs/sixsq/slipstream/webui/messages/views.cljs
  src/cljs/sixsq/slipstream/webui/usage/effects.cljs
  src/cljs/sixsq/slipstream/webui/usage/events.cljs
  src/cljs/sixsq/slipstream/webui/usage/spec.cljs
  src/cljs/sixsq/slipstream/webui/usage/subs.cljs
  src/cljs/sixsq/slipstream/webui/usage/utils.cljs
  src/cljs/sixsq/slipstream/webui/usage/views.cljs
  src/cljs/sixsq/slipstream/webui/utils/semantic_ui.cljs
  src/cljs/sixsq/slipstream/webui/utils/style.cljs
Labels: S40 Ready to validate
