Repository slipstream/SlipStreamWebUI, pull requests merged in 2018-03, with the labels that each got.

#106 avoid duplicate keys in operation buttons when data contains :key
  src/cljs/sixsq/slipstream/webui/utils/resource_details.cljs
Labels: P45 MF2C, S40 Ready to validate, T5 Bug

#107 ensure editor is rendered only with valid data
  src/cljs/sixsq/slipstream/webui/cimi_detail/views.cljs
Labels: P45 MF2C, S40 Ready to validate, T5 Bug

#108 switch from phantomjs to nashorn
  project.clj
Labels: P45 MF2C, S40 Ready to validate, T2 Task

#109 update layout
  project.clj
  src/cljs/sixsq/slipstream/webui/application/views.cljs
  src/cljs/sixsq/slipstream/webui/cimi/views.cljs
  src/cljs/sixsq/slipstream/webui/dashboard/views.cljs
  src/cljs/sixsq/slipstream/webui/deployment/views.cljs
  src/cljs/sixsq/slipstream/webui/deployment_detail/views.cljs
  src/cljs/sixsq/slipstream/webui/i18n/dictionary.cljs
  src/cljs/sixsq/slipstream/webui/main/views.cljs
  src/cljs/sixsq/slipstream/webui/metrics/utils.cljs
  src/cljs/sixsq/slipstream/webui/metrics/views.cljs
  src/cljs/sixsq/slipstream/webui/plot/plot.cljs
  src/cljs/sixsq/slipstream/webui/profile/views.cljs
  src/cljs/sixsq/slipstream/webui/settings/views.cljs
  src/cljs/sixsq/slipstream/webui/usage/views.cljs
  src/cljs/sixsq/slipstream/webui/utils/collapsible_card.cljs
  src/cljs/sixsq/slipstream/webui/utils/resource_details.cljs
Labels: S40 Ready to validate

#110 change breadcrumb size, separator; change sidebar close icon
  src/cljs/sixsq/slipstream/webui/application/views.cljs
  src/cljs/sixsq/slipstream/webui/main/views.cljs
Labels: S40 Ready to validate

#113 add support for href entry
  src/cljs/sixsq/slipstream/webui/utils/form_fields.cljs
Labels: S40 Ready to validate

#115 add welcome; move i18n; move profile; minor changes
  src/cljs/sixsq/slipstream/webui/authn/views.cljs
  src/cljs/sixsq/slipstream/webui/i18n/dictionary.cljs
  src/cljs/sixsq/slipstream/webui/i18n/views.cljs
  src/cljs/sixsq/slipstream/webui/main/views.cljs
  src/cljs/sixsq/slipstream/webui/welcome/views.cljs
Labels: P45 MF2C, S40 Ready to validate, T2 Task

#116 remove cljs-time, collect time utilities, add i18n to usage
  project.clj
  resources/public/css/webui.css
  src/cljs/sixsq/slipstream/webui/authn/views.cljs
  src/cljs/sixsq/slipstream/webui/deployment_detail/gantt.cljs
  src/cljs/sixsq/slipstream/webui/deployment_detail/utils.cljs
  src/cljs/sixsq/slipstream/webui/i18n/dictionary.cljs
  src/cljs/sixsq/slipstream/webui/i18n/events.cljs
  src/cljs/sixsq/slipstream/webui/i18n/views.cljs
  src/cljs/sixsq/slipstream/webui/profile/views.cljs
  src/cljs/sixsq/slipstream/webui/usage/utils.cljs
  src/cljs/sixsq/slipstream/webui/usage/views.cljs
  src/cljs/sixsq/slipstream/webui/utils/time.cljs
Labels: P45 MF2C, S40 Ready to validate, T2 Task

#117 add filter button; add legal page
  src/cljs/sixsq/slipstream/webui/cimi/events.cljs
  src/cljs/sixsq/slipstream/webui/cimi/spec.cljs
  src/cljs/sixsq/slipstream/webui/cimi/subs.cljs
  src/cljs/sixsq/slipstream/webui/cimi/views.cljs
  src/cljs/sixsq/slipstream/webui/deployment/events.cljs
  src/cljs/sixsq/slipstream/webui/deployment/spec.cljs
  src/cljs/sixsq/slipstream/webui/deployment/subs.cljs
  src/cljs/sixsq/slipstream/webui/deployment/views.cljs
  src/cljs/sixsq/slipstream/webui/i18n/dictionary.cljs
  src/cljs/sixsq/slipstream/webui/legal/views.cljs
  src/cljs/sixsq/slipstream/webui/main/views.cljs
  src/cljs/sixsq/slipstream/webui/usage/events.cljs
  src/cljs/sixsq/slipstream/webui/usage/spec.cljs
  src/cljs/sixsq/slipstream/webui/usage/subs.cljs
  src/cljs/sixsq/slipstream/webui/usage/views.cljs
  src/cljs/sixsq/slipstream/webui/utils/semantic_ui.cljs
Labels: P45 MF2C, S40 Ready to validate, T2 Task

#118 removable columns, fixed application targets, modal messages
  resources/public/css/webui.css
  src/cljs/sixsq/slipstream/webui/application/effects.cljs
  src/cljs/sixsq/slipstream/webui/application/views.cljs
  src/cljs/sixsq/slipstream/webui/cimi/events.cljs
  src/cljs/sixsq/slipstream/webui/cimi/views.cljs
  src/cljs/sixsq/slipstream/webui/main/views.cljs
Labels: P45 MF2C, S40 Ready to validate, T2 Task

#119 add messages page
  resources/public/css/webui.css
  src/cljs/sixsq/slipstream/webui/cimi/events.cljs
  src/cljs/sixsq/slipstream/webui/cimi/views.cljs
  src/cljs/sixsq/slipstream/webui/cimi_detail/events.cljs
  src/cljs/sixsq/slipstream/webui/deployment_detail/events.cljs
  src/cljs/sixsq/slipstream/webui/i18n/dictionary.cljs
  src/cljs/sixsq/slipstream/webui/messages/views.cljs
  src/cljs/sixsq/slipstream/webui/utils/collapsible_card.cljs
  src/cljs/sixsq/slipstream/webui/utils/response.cljs
  src/cljs/sixsq/slipstream/webui/utils/time.cljs
Labels: P45 MF2C, S40 Ready to validate, T2 Task

#120 metrics view broken
  src/cljs/sixsq/slipstream/webui/main/views.cljs
Labels: P45 MF2C, S40 Ready to validate, T5 Bug

#126 Query params and filter workaround controlled value issue
  src/cljs/sixsq/slipstream/webui/cimi/spec.cljs
  src/cljs/sixsq/slipstream/webui/cimi/views.cljs
  src/cljs/sixsq/slipstream/webui/deployment/views.cljs
  src/cljs/sixsq/slipstream/webui/history/effects.cljs
  src/cljs/sixsq/slipstream/webui/history/utils.cljs
  src/cljs/sixsq/slipstream/webui/main/events.cljs
Labels: S40 Ready to validate
