Repository slipstream/SlipStreamWebUI, pull requests merged in 2019-01, with the labels that each got.

#321 use href instead of javascript for downloading report
  src/cljs/sixsq/slipstream/webui/deployment_detail/events.cljs
  src/cljs/sixsq/slipstream/webui/deployment_detail/views.cljs
Labels: S40 Ready to validate, T5 Bug

#322 service offer keywords
  src/cljs/sixsq/slipstream/webui/deployment_dialog/utils.cljs
Labels: P22 GNSS, S40 Ready to validate, T5 Bug

#324 Provide dataset id as string in service offer map
  src/cljs/sixsq/slipstream/webui/data/effects.cljs
  src/cljs/sixsq/slipstream/webui/data/events.cljs
  src/cljs/sixsq/slipstream/webui/data/spec.cljs
  src/cljs/sixsq/slipstream/webui/deployment_dialog/events.cljs
  src/cljs/sixsq/slipstream/webui/deployment_dialog/utils.cljs
Labels: P22 GNSS, S40 Ready to validate

#326 confirmation message before stoping or deleting deployment
  src/cljs/sixsq/slipstream/webui/deployment/views.cljs
  src/cljs/sixsq/slipstream/webui/i18n/dictionary.cljs
Labels: S40 Ready to validate

#342 revert to URL
  src/cljs/sixsq/slipstream/webui/deployment/views.cljs
  src/cljs/sixsq/slipstream/webui/i18n/dictionary.cljs
Labels: P22 GNSS, S40 Ready to validate, T2 Task

#343 change deployment card link
  src/cljs/sixsq/slipstream/webui/deployment/views.cljs
  src/cljs/sixsq/slipstream/webui/i18n/dictionary.cljs
Labels: P22 GNSS, S40 Ready to validate, T2 Task
